$(document).ready(function(){$('.ajax-addtocart').click(function(){var product=$(this);var module=product.attr('data-module');var modal=UIkit.modal('#modal-cart',{bgclose:false,});if(module!='redirect'){modal.show();$('#modal-cart .cart-content').html('Loading...');}$.post(BASE_URL+'products/ajax/cart/addtocart',{id:product.attr('data-id'),quantity:product.attr('data-quantity'),},function(data){if(module=='redirect'){window.location.href=BASE_URL+'dat-mua';}var json=JSON.parse(data);$('#modal-cart .cart-content').html(json.html);$('#ajax-home-cart-quantity').html(json.item);});return false;});$(document).on('click','#ec-module-cart .augment',function(){var item=$(this);var quantity=parseInt($(this).parent().find('.quantity').val());quantity=quantity+1;item.parent().find('.quantity').val(quantity);ajax_cart_update();return false;});$(document).on('click','#ec-module-cart .abate',function(){var item=$(this);var quantity=parseInt($(this).parent().find('.quantity').val());if(quantity<=1){quantity=1}else{quantity=quantity-1;}item.parent().find('.quantity').val(quantity);ajax_cart_update();return false;});$(document).on('click','#ec-module-cart .delete',function(){var item=$(this);item.parent().parent().parent().parent().parent().find('.quantity').val(0);item.parent().parent().parent().parent().parent().addClass('uk-hidden').removeClass('item');ajax_cart_update();return false;});$(document).on('click','.ec-cart-continue',function(){UIkit.modal('#modal-cart').hide();return false;});$('.augment').click(function(){var num_order=parseInt($(this).parent().find('.quantity').val());num_order+=1;$(this).parent().find('.quantity').val(num_order);});$('.abate').click(function(){var cart_class=$(this).attr('data-cart');var num_order=parseInt($(this).parent().find('.quantity').val());if(num_order<=1){num_order=1}else{num_order-=1;}$(this).parent().find('.quantity').val(num_order);});var time;$('.keyword').on('keyup',function(){var keyword=$(this).val();var numberKey=keyword.length;if(numberKey>=3){clearTimeout(time);time=setTimeout(function(){$.ajax({url:'searchs/ajax/searchs/search',method:'POST',dataType:'JSON',data:{keyword:keyword},complete:function(data){var datajson=JSON.parse(data.responseText);$('.header-search .searchResult').show();$('.header-search .searchResult').html(datajson.html);}});},200);}else{$('.header-search .searchResult').hide();}});});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);}function ajax_cart_update(){$.post(BASE_URL+'products/ajax/cart/updatetocart',$('#ajax-cart-form').serialize(),function(data){var price=JSON.parse(data);$('#ajax-cart-form').html(price.html);});return false;}


$('#emailForm').on('submit',function(){
	var fullname=$('#fullname').val();
	var phone=$('#phone').val();
	var message=$('#message').val();
	var modal=UIkit.modal('#modal-alert',{bgclose:false,});
	var formURL = 'ajax/frontend/action/send_email_to_take_information';
	$.post(formURL,{fullname:fullname,phone:phone,message:message},function(data){
	// modal.show();
	$('#ajax_result').html('Đã gửi yêu cầu');
	// $('#modal-alert .alert-content').html(json.message);
	});
	
	return false;
});